lithops:
  backend: one
one:
  docker_user: # Docker hub username
  docker_pass: # Docker hub password
  runtime_cpu: # number of vCPU x POD (default: 1)
  runtime_memory: # amount of memory x POD (default: 512MiB)

  kubecfg_path': # PATH were kubeconfig will be stored (default: `/tmp/kubeconfig`)
  auto_scale: # options: `'all'` (default), `'up'`, `'down'`, `'none'`
  minimum_nodes: # minimum number of nodes (default: 1)
  maximum_nodes: # maximum number of nodes (default: 3)